@hostname = http://localhost
@port = 3001
@host = {{hostname}}:{{port}}
@contentType = application/json

# Retrieving or Read Data from DB
# GET {{host}}/users

# retrieving or Read Data from DB By ID
# GET {{host}}/users/62ff7b0c4ef2f9ab65426906  

# retrieving or Read  AND Paginate Data from DB 
# GET {{host}}/todos?page=1&limit=10

# Create a new Data
# POST {{host}}/todos HTTP/1.1
# content-type: application/json

# {
#     "title": " testing adding todo",
#     "selected": true
# }

# Update Data from DB By ID
# PATCH {{host}}/update/631097c122f9c0887c3e6d89 HTTP/1.1
# content-type: application/json

# {
#     "title": " new todo app",
#     "selected": true
# }

# Delete Data By Id from DB
# DELETE  {{host}}/delete/631097c122f9c0887c3e6d89 HTTP/1.1
# content-type: application/json

# {
#     "title": " new todo app",
#     "selected": true
# }

